### ISSUE TITLE
Container stopping frequently

### ISSUE THREAD

**Issue by adityavijjanT** [pryorda/vmware_exporter#112]
We are using AWS ECS and vmexporter container is restarting at every 15 mins, i have configured 
scrap interval of 5 mins and have 30 esxi hosts added.

Have also checked logs but seems to be very generic like start collecting metrix/ stop collecting metrix.

Also opened a ticket with AWS and they suggested that health check is failing so container is stopping.

- job_name: 'esxi_hosts'
    scheme: http
    scrape_interval: 5m
    scrape_timeout: 5m
    file_sd_configs:
      - files:
        - '/etc/prometheus/vm/esxi_hosts.json'
    params:
      section: [esx]
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: esxihost:9272  # The vmw exporter's real hostname:port.

**Comment by Jc2k** [comment]
What health checks have you set up?

**Comment by adityavijjanT** [comment]
200-499

**Comment by Jc2k** [comment]
I mean are you using the `/healthz' endpoint for healthchecks or something else? That endpoint doesn't do any real checking only returns 200, the only other outcome would be a TCP timeout because of a connection backlog or a connection reset if the thing had crashed out.

Is it stable if you monitor a smaller set of esx hosts?

Most vmware_exporter users monitor their vsphere instance rather than each esx host individually. We've seen deployments that size where the exporter worked just by connecting to vsphere. The vsphere API is slow, but targetting ESXi directly seems to be slower. I'm wondering if it can't check 32 hosts in 5 minutes so a backlog is building up, in which case you might need an exporter for every 8 hosts or something (exact number will need some experimenting).

**Comment by adityavijjanT** [comment]
We have QA exporter working fine with same config and have only 4 ESXI hosts, let me increase scrap interval (our requirement is 5 min) to 10 mins and check the performance.

I have not configured vm exporter to vcenter as i need vm metrics per esxi hosts per site.

**Comment by Jc2k** [comment]
I think you get the same metrics if you scrape the vcenter directly, with labels to tell which datacenter, compute cluster, esx instance, etc

**Comment by adityavijjanT** [comment]
You mean in 5 min scrap i can have metrix for the 30 esxi host and 500 vms via vcenter  instead of collecting metrix for each esxi.

**Comment by adityavijjanT** [comment]
ok so i think something wrong with my container, can you send me link for docker hub which container is latest.

**Comment by Jc2k** [comment]
The official image is here: https://hub.docker.com/r/pryorda/vmware_exporter

`v0.9.0` was released 3 days ago.

**Comment by kremers** [comment]
Might be originating from stall connections which is fixed.

**Comment by adityavijjanT** [comment]
I have increased the timeout value to 10 mins and my container is stable, now i am checking new image with 5 min timeout.

**Comment by kremers** [comment]
Any result so far?

**Comment by adityavijjanT** [comment]
I have integrated Vcenter (4 esxi) with exporter in dev environment and getting matrix with 5 min interval, now will check prod vcenter (30 esxi).

**Comment by pryorda** [comment]
Still looking good?

**Comment by adityavijjanT** [comment]
I am able to crap with 5 min interval, no issues so far.

**Comment by pryorda** [comment]
Closing out for now
