### ISSUE TITLE
Problem with prometheus function : "rate" 

### ISSUE THREAD

**Issue by SckyzO** [pryorda/vmware_exporter#177]
Hello World, 

I use vmware exporter to generate dashboard for billing for our clients. In my enterprise we have to charge VMs to the number of vCPU, number of Memory and size of hard disk drives. 
But, I have a problem. 
I want to use "rate function of prometheus" with this metric for example : vmware_vm_num_cpu, and result is always : 0

My use case : 
```
vmware_vm_num_cpu{vm_name="DVOTEST0000"}

vmware_vm_num_cpu{cluster_name="Cpt-Cluster", dc_name="DevopsCannes", host_name="cadvovmwp54", instance="vmware_exporter:9272", job="vmware_exporter", vm_name="DVOTEST0000"}	8
```
With rate function : 
```
rate(vmware_vm_num_cpu{vm_name="DVOTEST0014"}[5m]) 

{cluster_name="Cpt-Cluster", dc_name="DevopsCannes", host_name="cadvovmwp54", instance="vmware_exporter:9272", job="vmware_exporter", vm_name="DVOTEST0000"}	0
```
But i have time serie metric ...

```
vmware_vm_num_cpu{vm_name="DVOTEST0014"}[5m]

vmware_vm_num_cpu{cluster_name="Cpt-Cluster", dc_name="DevopsCannes", host_name="cadvovmwp55", instance="vmware_exporter:9272", job="vmware_exporter", vm_name="DVOTEST0014"}	1 @1583144008.979
1 @1583144023.979
1 @1583144038.979
1 @1583144053.979
1 @1583144068.979
1 @1583144083.979
1 @1583144098.979
1 @1583144113.979
1 @1583144128.979
1 @1583144143.979
1 @1583144158.979
1 @1583144173.979
1 @1583144188.979
1 @1583144203.979
1 @1583144218.979
1 @1583144233.98
1 @1583144248.979
1 @1583144263.979
1 @1583144278.979
1 @1583144293.979
```

I don't understand why I can't use "rate" function. But when I use "avg_over_time" function, it's works! But I don't want to use this function :) 

```
avg_over_time(vmware_vm_num_cpu{vm_name="DVOTEST00000}[5m])

{cluster_name="Cpt-Cluster", dc_name="DevopsCannes", host_name="cadvovmwp54", instance="vmware_exporter:9272", job="vmware_exporter", vm_name="DVOTEST00000"}	8
```

Could someone help me understand why it is not working and how to make it work?

Regard,

**Comment by dannyk81** [comment]
`vmware_vm_num_cpu` is a gauge and indicates that amount of vCPUs allocated to a VM, this value doesn't change over the runtime of the VM and you can't use a `rate()` function on gauge metrics, only on counters.

> rate(v range-vector) calculates the per-second average rate of increase of the time series in the range vector.

> rate should only be used with counters. It is best suited for alerting, and for graphing of slow-moving counters.

https://prometheus.io/docs/prometheus/latest/querying/functions/#rate

`vmware_vm_num_cpu`'s value doesn't change over time, all the samples will return the same value, since the number of vCPUs allocated to the VM doesn't change during VM runtime, so given that all samples in a range vector are the same the rate will be 0 - since there is no increase in value the rate of increase is 0.

`avg_over_time` calculates the average of all samples in a range vector (`[5m]` in your case), so an average of n-samples of 8 is... 8.

Given your requirement: _"charge VMs to the number of vCPU, number of Memory and size of hard disk drives"_ - why do you need to use `rate()` or any other aggregating function? I'm not sure what you are trying to achieve with this query...

You should clarify to yourself what is that you expect your query to return and what that value should reflect, once you defined your requirement use the appropriate metrics and/or functions.

**Comment by dannyk81** [comment]
@SckyzO I'm closing this, if there's any issue with exporter you can open another issue.
