### ISSUE TITLE
Mixed up of vm custom attributes value

### ISSUE THREAD

**Issue by zoic21** [pryorda/vmware_exporter#295]
Hello,

I got a wired issue, I don't known if it's related to vmware_exporter, prometheus or grafana, but I got I mixed up of possible value in custom attribute.

I create a custom attribute APP and custom attribute ENVIRONEMENT and when I ask grafana to list all possible value for APP (for exemple) attribute I get possible value for APP and ENVIRONEMENT and other value. I can't understand why...

Does someone also get this issue ?

Thank in advance,

**Comment by pryorda** [comment]
I have not observed this issue. Closing for now. We can reopen if this appears to be a theme.

**Comment by ApocBoots** [comment]
Hello Guys

I have been experiencing a similar issue for all vmware_vm_* metrics:
Example:

![image](https://user-images.githubusercontent.com/105059474/175980023-addc24bc-1158-437e-af44-b46080057408.png)


In Grafana, i see gaps in vmware_vm_snapshot_timestamp_seconds.
It appears as if there were 2 Snaphots on "vm1", one named "snapshot1" and one named "Debian 8".
However, in vCenter vm1 only has 1 snapshot (snapshot1) and "Debian 8" is the value of a custom attribute called OS_Version. The values are switched, creating two separate timeseries instead of one.

The fields "Contact" and abc_information are also changed somehow (see "Foo" & "Bar")

Does someone have an idea why this is happening?

Thanks and kind regards
