### ISSUE TITLE
The vmware_vm_mem_usage_average metric is just an average, and I don't know the actual memory usage

### ISSUE THREAD

**Issue by hurongyang** [pryorda/vmware_exporter#68]
The vmware_vm_mem_usage_average metric is just an average, and I don't know the actual memory usage

**Comment by Jc2k** [comment]
Hi @hurongyang - I don't know if we have enough information to adequately resolve this issue. Is there an alternative metric in ESX that you think would be useful to export?

`vmware_vm_mem_usage_average` is a scrape of a PerformanceCounterInfo metric. They are documented [here](https://www.vmware.com/support/developer/converter-sdk/conv51_apireference/memory_counters.html). It's defined as "Memory usage as percentage of total configured or available memory.".

`average` is the metric 'rollup', very few of these metrics have a `latest` option, but some do have `minimum` and `maximum` rollups. We always fetch the latest average rollup when we scrape. My understanding is that this might be an average over the last 5m, or possibly over the last 20s its not entirely clear. Do you have reason to believe its not?

Are you ok with an average but would prefer the `consumed` or `granted` metrics rather than a percentage?

**Comment by hurongyang** [comment]
@Jc2k @dannyk81 Thank you very much for your answer，I already know this metrics

**Comment by dannyk81** [comment]
@hurongyang I'm closing this issue, feel free to re-open or submit a new one if needed.
